In [160]:
import numpy as np
import pandas as pd

In [161]:
data = pd.read_csv("C:\\Users\\Abarna V\\Desktop\\End semester AML Laboratory (Dataset)\\NAIVE BAYES\\heart.csv")
data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [162]:
x = data.iloc[:,0:13]
x

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  
0         2   2     3  
1         0   0     3  
2         0   0     3  
3         2   1     3  
4         1   3     2  
...     ...  ..   ...  
1020      2   0     2  
1021      1   1     3  
1022      1   1     2  
1023      2   0     2  
1024      1   1     3  

[1025 rows x 13 columns]

In [163]:
y = data.iloc[:,13]
y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [164]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(x,y,test_size=0.25)

In [165]:
# importing standard scaler
from sklearn.preprocessing import StandardScaler
# scalling the input data
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [166]:
x_train

array([[ 0.29469212,  0.65181351, -0.90865363, ..., -0.63795756,
         0.2163035 ,  1.08914928],
       [-1.47173559, -1.53418115,  0.05655521, ...,  0.9737247 ,
        -0.7384154 , -0.53821774],
       [ 1.72991464,  0.65181351,  0.05655521, ...,  0.9737247 ,
        -0.7384154 , -0.53821774],
       ...,
       [-0.25731654,  0.65181351,  1.02176404, ...,  0.9737247 ,
        -0.7384154 ,  1.08914928],
       [-0.8093252 ,  0.65181351,  1.02176404, ...,  0.9737247 ,
        -0.7384154 , -0.53821774],
       [ 0.73629905, -1.53418115, -0.90865363, ..., -0.63795756,
        -0.7384154 ,  1.08914928]])

In [167]:
x_test

array([[-0.30175537,  0.69066019,  2.03774447, ..., -0.58306984,
        -0.71433326, -2.04588021],
       [ 0.46825585,  0.69066019,  1.04588779, ..., -0.58306984,
         0.31127371, -2.04588021],
       [-2.17178261,  0.69066019, -0.93782558, ..., -0.58306984,
        -0.71433326,  1.09317181],
       ...,
       [-1.40177139,  0.69066019,  0.0540311 , ...,  1.06362191,
        -0.71433326, -0.4763542 ],
       [-0.96176498, -1.44789003, -0.93782558, ..., -0.58306984,
        -0.71433326, -0.4763542 ],
       [ 0.35825425, -1.44789003, -0.93782558, ..., -0.58306984,
         1.33688069, -2.04588021]])

In [170]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
model = AdaBoostClassifier(base_estimator=nb, n_estimators=5)
model.fit(x_train, y_train)

AdaBoostClassifier(base_estimator=GaussianNB(), n_estimators=5)

In [171]:
y_predict = model.predict(x_test)
y_predict

array([1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0], dtype=int64)

In [172]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
accuracy_score(y_test, y_predict)

0.7237354085603113

In [173]:
confusion_matrix(y_test, y_predict)

array([[94, 28],
       [43, 92]], dtype=int64)

In [174]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.69      0.77      0.73       122
           1       0.77      0.68      0.72       135

    accuracy                           0.72       257
   macro avg       0.73      0.73      0.72       257
weighted avg       0.73      0.72      0.72       257

