In [241]:
import pandas as pd
import numpy as np

In [242]:
df = pd.read_csv("C:\\Users\\Abarna V\\Desktop\\End semester AML Laboratory (Dataset)\RANDOM FOREST\\temperature.csv")
df

year  month  day   week  temp_2  temp_1  average  actual  friend
0    2019      1    1    Fri      45      45     45.6      45      29
1    2019      1    2    Sat      44      45     45.7      44      61
2    2019      1    3    Sun      45      44     45.8      41      56
3    2019      1    4    Mon      44      41     45.9      40      53
4    2019      1    5   Tues      41      40     46.0      44      41
..    ...    ...  ...    ...     ...     ...      ...     ...     ...
343  2019     12   27   Tues      42      42     45.2      47      47
344  2019     12   28    Wed      42      47     45.3      48      58
345  2019     12   29  Thurs      47      48     45.3      48      65
346  2019     12   30    Fri      48      48     45.4      57      42
347  2019     12   31    Sat      48      57     45.5      40      57

[348 rows x 9 columns]

In [243]:
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()

# Converting string labels into numbers.
df['week'] =le.fit_transform(df['week'])
df['week'].unique()
df

year  month  day  week  temp_2  temp_1  average  actual  friend
0    2019      1    1     0      45      45     45.6      45      29
1    2019      1    2     2      44      45     45.7      44      61
2    2019      1    3     3      45      44     45.8      41      56
3    2019      1    4     1      44      41     45.9      40      53
4    2019      1    5     5      41      40     46.0      44      41
..    ...    ...  ...   ...     ...     ...      ...     ...     ...
343  2019     12   27     5      42      42     45.2      47      47
344  2019     12   28     6      42      47     45.3      48      58
345  2019     12   29     4      47      48     45.3      48      65
346  2019     12   30     0      48      48     45.4      57      42
347  2019     12   31     2      48      57     45.5      40      57

[348 rows x 9 columns]

In [244]:
df.tail()

year  month  day  week  temp_2  temp_1  average  actual  friend
343  2019     12   27     5      42      42     45.2      47      47
344  2019     12   28     6      42      47     45.3      48      58
345  2019     12   29     4      47      48     45.3      48      65
346  2019     12   30     0      48      48     45.4      57      42
347  2019     12   31     2      48      57     45.5      40      57

In [245]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348 entries, 0 to 347
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   year     348 non-null    int64  
 1   month    348 non-null    int64  
 2   day      348 non-null    int64  
 3   week     348 non-null    int32  
 4   temp_2   348 non-null    int64  
 5   temp_1   348 non-null    int64  
 6   average  348 non-null    float64
 7   actual   348 non-null    int64  
 8   friend   348 non-null    int64  
dtypes: float64(1), int32(1), int64(7)
memory usage: 23.2 KB


In [246]:
df.describe()

year       month         day        week      temp_2      temp_1  \
count   348.0  348.000000  348.000000  348.000000  348.000000  348.000000   
mean   2019.0    6.477011   15.514368    3.005747   62.652299   62.701149   
std       0.0    3.498380    8.772982    2.004310   12.165398   12.120542   
min    2019.0    1.000000    1.000000    0.000000   35.000000   35.000000   
25%    2019.0    3.000000    8.000000    1.000000   54.000000   54.000000   
50%    2019.0    6.000000   15.000000    3.000000   62.500000   62.500000   
75%    2019.0   10.000000   23.000000    5.000000   71.000000   71.000000   
max    2019.0   12.000000   31.000000    6.000000  117.000000  117.000000   

          average      actual      friend  
count  348.000000  348.000000  348.000000  
mean    59.760632   62.543103   60.034483  
std     10.527306   11.794146   15.626179  
min     45.100000   35.000000   28.000000  
25%     49.975000   54.000000   47.750000  
50%     58.200000   62.500000   60.000000  
75%     69.025000   71.000000   71.000000  
max     77.400000   92.000000   95.000000

In [247]:
x = df.iloc[:,:-1]
x

year  month  day  week  temp_2  temp_1  average  actual
0    2019      1    1     0      45      45     45.6      45
1    2019      1    2     2      44      45     45.7      44
2    2019      1    3     3      45      44     45.8      41
3    2019      1    4     1      44      41     45.9      40
4    2019      1    5     5      41      40     46.0      44
..    ...    ...  ...   ...     ...     ...      ...     ...
343  2019     12   27     5      42      42     45.2      47
344  2019     12   28     6      42      47     45.3      48
345  2019     12   29     4      47      48     45.3      48
346  2019     12   30     0      48      48     45.4      57
347  2019     12   31     2      48      57     45.5      40

[348 rows x 8 columns]

In [248]:
y = df.iloc[:,-1]
y

0      29
1      61
2      56
3      53
4      41
       ..
343    47
344    58
345    65
346    42
347    57
Name: friend, Length: 348, dtype: int64

In [249]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=99)

In [250]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(criterion = "gini", max_depth=2, min_samples_split=2,random_state=0 )

In [251]:
clf.fit(x_train,y_train)

RandomForestClassifier(max_depth=2, random_state=0)

In [252]:
y_pred=clf.predict(x_test)
y_pred

array([70, 58, 64, 56, 58, 58, 70, 64, 64, 62, 58, 58, 58, 62, 58, 58, 39,
       70, 81, 58, 58, 70, 62, 64, 61, 66, 62, 62, 61, 61, 58, 58, 81, 56,
       70, 58, 81, 61, 81, 58, 54, 64, 56, 58, 64, 58, 56, 65, 64, 58, 70,
       45, 64, 62, 70, 62, 61, 64, 62, 64, 90, 61, 66, 62, 70, 58, 58, 64,
       61, 58], dtype=int64)

In [253]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]], dtype=int64)

In [254]:
from sklearn import metrics
meanAbErr = metrics.mean_absolute_error(y_test, y_pred)
meanSqErr = metrics.mean_squared_error(y_test, y_pred)
rootMeanSqErr = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
print('R squared: {:.2f}'.format(clf.score(x,y)*100))
print('Mean Absolute Error:', meanAbErr)
print('Mean Square Error:', meanSqErr)
print('Root Mean Square Error:', rootMeanSqErr)

R squared: 15.23
Mean Absolute Error: 9.557142857142857
Mean Square Error: 154.15714285714284
Root Mean Square Error: 12.416003497790376


In [255]:
clf.predict([[2019,12,28,6,42,47,45.3,48]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([58], dtype=int64)